# Poetry Aliases
alias ptr="poetry"
alias ptri="ptr install"
alias ptru="ptr update"
alias ptrl="ptr list"
alias ptrc="ptr check"
alias ptrs="ptr show"
alias ptrp="ptr publish"
alias ptrd="ptr dev"
alias ptrb="ptr build"