# Flatpak Aliases
alias fp:i="flatpak install"
alias fp:up="flatpak update"
alias fp:r="flatpak run"
alias fp:s="flatpak search"
alias fp:un="flatpak uninstall"
alias fp:ra="flatpak remote-add --if-not-exists"
alias fp:rm="flatpak remote-delete --if-exists"
alias fp:l="flatpak list"
alias fp:ls="flatpak list-remote"